"""users, profile and pantry

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 10:39:11.230987
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_subject", name=op.f("uq_users_auth_subject")),
    )
    op.create_table(
        "allergies",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("allergens", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("avoid_food_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_allergies_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_allergies")),
    )
    op.create_table(
        "body_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sex", sa.String(length=8), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("activity", sa.String(length=16), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_body_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_body_profiles")),
    )
    op.create_table(
        "goals",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("goal", sa.String(length=16), nullable=True),
        sa.Column("kcal_min", sa.Float(), nullable=False),
        sa.Column("kcal_max", sa.Float(), nullable=False),
        sa.Column("calorie_floor", sa.Float(), nullable=False),
        sa.Column("max_daily_deficit", sa.Float(), nullable=False),
        sa.Column("protein_g_min", sa.Float(), nullable=True),
        sa.Column("protein_g_max", sa.Float(), nullable=True),
        sa.Column("fat_g_min", sa.Float(), nullable=True),
        sa.Column("fat_g_max", sa.Float(), nullable=True),
        sa.Column("carbs_g_min", sa.Float(), nullable=True),
        sa.Column("carbs_g_max", sa.Float(), nullable=True),
        sa.Column("weekly_budget_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_goals")),
    )
    op.create_table(
        "pantry_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("grams", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("approx", sa.Boolean(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["food_id"], ["foods.id"], name=op.f("fk_pantry_items_food_id_foods")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pantry_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pantry_items")),
    )
    op.create_index(op.f("ix_pantry_items_user_id"), "pantry_items", ["user_id"], unique=False)
    op.create_table(
        "preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("diet", sa.String(length=16), nullable=True),
        sa.Column("liked_cuisines", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("disliked_cuisines", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("liked_food_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("disliked_food_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_preferences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_preferences")),
    )
    op.create_index(
        "ix_foods_description_trgm",
        "foods",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_foods_description_trgm",
        table_name="foods",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_table("preferences")
    op.drop_index(op.f("ix_pantry_items_user_id"), table_name="pantry_items")
    op.drop_table("pantry_items")
    op.drop_table("goals")
    op.drop_table("body_profiles")
    op.drop_table("allergies")
    op.drop_table("users")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
