"""meal plans and shopping lists

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 14:35:12.362599
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("days", sa.SmallInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("planner", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("objective", sa.BigInteger(), nullable=True),
        sa.Column("solve_ms", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["meal_plans.id"],
            name=op.f("fk_meal_plans_parent_id_meal_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_meal_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_plans")),
        sa.UniqueConstraint(
            "user_id",
            "start_date",
            "version",
            name=op.f("uq_meal_plans_user_id_start_date_version"),
        ),
    )
    op.create_index(
        "ix_meal_plans_user_created", "meal_plans", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "plan_meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.SmallInteger(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("portions", sa.SmallInteger(), nullable=False),
        sa.Column("kcal", sa.Integer(), nullable=False),
        sa.Column("protein_g", sa.Integer(), nullable=False),
        sa.Column("fat_g", sa.Integer(), nullable=False),
        sa.Column("carbs_g", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["meal_plans.id"],
            name=op.f("fk_plan_meals_plan_id_meal_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], name=op.f("fk_plan_meals_recipe_id_recipes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_meals")),
        sa.UniqueConstraint("plan_id", "day", "slot", name=op.f("uq_plan_meals_plan_id_day_slot")),
    )
    op.create_table(
        "shopping_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("grams", sa.Integer(), nullable=False),
        sa.Column("cost_minor", sa.Integer(), nullable=False),
        sa.Column("staple", sa.Boolean(), nullable=False),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"], ["foods.id"], name=op.f("fk_shopping_items_food_id_foods")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["meal_plans.id"],
            name=op.f("fk_shopping_items_plan_id_meal_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_items")),
        sa.UniqueConstraint("plan_id", "food_id", name=op.f("uq_shopping_items_plan_id_food_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_items")
    op.drop_table("plan_meals")
    op.drop_index("ix_meal_plans_user_created", table_name="meal_plans")
    op.drop_table("meal_plans")
    # ### end Alembic commands ###
