/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up and serving requests.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: every backing service (Postgres, Redis) answers.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Delete the account and all its data (GDPR). The identity-provider account is deleted
         *     by the client with its own SDK.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Me
         * @description Everything stored about the user, as JSON (GDPR data portability).
         */
        get: operations["exportMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goals */
        get: operations["getGoals"];
        /**
         * Put Goals
         * @description Refuses unsafe or impossible targets (calorie floor, max deficit vs estimated needs).
         */
        put: operations["putGoals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/body": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Body */
        get: operations["getBody"];
        /** Put Body */
        put: operations["putBody"];
        post?: never;
        /** Delete Body */
        delete: operations["deleteBody"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["getPreferences"];
        /** Put Preferences */
        put: operations["putPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/allergies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Allergies */
        get: operations["getAllergies"];
        /**
         * Put Allergies
         * @description Hard constraints: no planned recipe will contain these (enforced by the solver, M3).
         */
        put: operations["putAllergies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuisines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cuisines
         * @description Cuisines of the seeded recipes, for preference pickers.
         */
        get: operations["listCuisines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allergens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Allergens */
        get: operations["listAllergens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Curated ingredient names first ("onion" -> "Onions, raw"), then trigram matches.
         */
        get: operations["searchFoods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Food */
        get: operations["getFood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pantry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description Soonest-expiring first; items without a date last.
         */
        get: operations["listPantry"];
        put?: never;
        /** Add Item */
        post: operations["addPantryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pantry/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["deletePantryItem"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["updatePantryItem"];
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Plan
         * @description The most recently created plan, or null if there is none.
         */
        get: operations["getCurrentPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/shopping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shopping List */
        get: operations["getShoppingList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/shopping/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Shopping Item */
        patch: operations["patchShoppingItem"];
        trace?: never;
    };
    "/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["getRecipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @enum {string}
         */
        Activity: "sedentary" | "light" | "moderate" | "active" | "very_active";
        /**
         * Allergen
         * @enum {string}
         */
        Allergen: "celery" | "gluten" | "crustaceans" | "eggs" | "fish" | "lupin" | "milk" | "molluscs" | "mustard" | "tree_nuts" | "peanuts" | "sesame" | "soy" | "sulphites";
        /** AllergenOption */
        AllergenOption: {
            code: components["schemas"]["Allergen"];
            /** Label */
            label: string;
        };
        /** AllergiesIn */
        AllergiesIn: {
            /** Allergens */
            allergens?: components["schemas"]["Allergen"][];
            /** Avoid Food Ids */
            avoid_food_ids?: number[];
        };
        /** AllergiesOut */
        AllergiesOut: {
            /** Allergens */
            allergens?: components["schemas"]["Allergen"][];
            /** Avoid Food Ids */
            avoid_food_ids?: number[];
            /** Avoid Foods */
            avoid_foods?: components["schemas"]["FoodSummary"][];
        };
        /** BandOut */
        BandOut: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** BodyIn */
        BodyIn: {
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            activity: components["schemas"]["Activity"];
        };
        /** BodyOut */
        BodyOut: {
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            activity: components["schemas"]["Activity"];
            /** Tdee Kcal */
            tdee_kcal: number;
            /** Suggestions */
            suggestions: {
                [key: string]: components["schemas"]["SuggestedTargets"];
            };
        };
        /** DayOut */
        DayOut: {
            /** Day */
            day: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Meals */
            meals: components["schemas"]["MealOut"][];
            totals: components["schemas"]["MacrosOut"];
        };
        /** FoodDetail */
        FoodDetail: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Category */
            category: string | null;
            /** Kcal */
            kcal: number | null;
            /** Units */
            units: components["schemas"]["FoodUnit"][];
        };
        /** FoodSummary */
        FoodSummary: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Category */
            category: string | null;
            /** Kcal */
            kcal: number | null;
        };
        /**
         * FoodUnit
         * @description A unit the user can enter for this food, with its weight when one unit is known.
         */
        FoodUnit: {
            /** Unit */
            unit: string;
            /** Grams Each */
            grams_each?: number | null;
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "lose" | "maintain" | "gain";
        /** GoalsIn */
        GoalsIn: {
            goal?: components["schemas"]["Goal"] | null;
            /** Kcal Min */
            kcal_min: number;
            /** Kcal Max */
            kcal_max: number;
            /**
             * Calorie Floor
             * @default 1200
             */
            calorie_floor: number;
            /**
             * Max Daily Deficit
             * @default 1000
             */
            max_daily_deficit: number;
            /** Protein G Min */
            protein_g_min?: number | null;
            /** Protein G Max */
            protein_g_max?: number | null;
            /** Fat G Min */
            fat_g_min?: number | null;
            /** Fat G Max */
            fat_g_max?: number | null;
            /** Carbs G Min */
            carbs_g_min?: number | null;
            /** Carbs G Max */
            carbs_g_max?: number | null;
            /** Weekly Budget Minor */
            weekly_budget_minor?: number | null;
            /**
             * Currency
             * @default GBP
             * @enum {string}
             */
            currency: "GBP" | "EUR" | "USD";
        };
        /** GoalsOut */
        GoalsOut: {
            goal?: components["schemas"]["Goal"] | null;
            /** Kcal Min */
            kcal_min: number;
            /** Kcal Max */
            kcal_max: number;
            /**
             * Calorie Floor
             * @default 1200
             */
            calorie_floor: number;
            /**
             * Max Daily Deficit
             * @default 1000
             */
            max_daily_deficit: number;
            /** Protein G Min */
            protein_g_min?: number | null;
            /** Protein G Max */
            protein_g_max?: number | null;
            /** Fat G Min */
            fat_g_min?: number | null;
            /** Fat G Max */
            fat_g_max?: number | null;
            /** Carbs G Min */
            carbs_g_min?: number | null;
            /** Carbs G Max */
            carbs_g_max?: number | null;
            /** Weekly Budget Minor */
            weekly_budget_minor?: number | null;
            /**
             * Currency
             * @default GBP
             * @enum {string}
             */
            currency: "GBP" | "EUR" | "USD";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * MacrosOut
         * @description Energy and macros as whole numbers (kcal, grams).
         */
        MacrosOut: {
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carbs G */
            carbs_g: number;
        };
        /** Me */
        Me: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            profile: components["schemas"]["ProfileStatus"];
            /** Setup Complete */
            setup_complete: boolean;
        };
        /** MealOut */
        MealOut: {
            slot: components["schemas"]["Slot"];
            recipe: components["schemas"]["RecipeCard"];
            /**
             * Portions
             * @description half-servings: 2 = one serving
             */
            portions: number;
            /** Servings */
            servings: number;
            nutrition: components["schemas"]["MacrosOut"];
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * Status
             * @default planned
             * @enum {string}
             */
            status: "planned" | "eaten" | "skipped" | "off_plan";
        };
        /** NutrientBands */
        NutrientBands: {
            kcal?: components["schemas"]["BandOut"] | null;
            protein_g?: components["schemas"]["BandOut"] | null;
            fat_g?: components["schemas"]["BandOut"] | null;
            carbs_g?: components["schemas"]["BandOut"] | null;
        };
        /** PantryItemIn */
        PantryItemIn: {
            /** Food Id */
            food_id: number;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /**
             * Approx
             * @default false
             */
            approx: boolean;
            /** Expires On */
            expires_on?: string | null;
        };
        /** PantryItemOut */
        PantryItemOut: {
            /** Id */
            id: number;
            food: components["schemas"]["FoodSummary"];
            /** Grams */
            grams: number;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Approx */
            approx: boolean;
            /** Expires On */
            expires_on: string | null;
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PantryItemPatch */
        PantryItemPatch: {
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
            /** Approx */
            approx?: boolean | null;
            /** Expires On */
            expires_on?: string | null;
        };
        /** PlanOut */
        PlanOut: {
            /** Id */
            id: number;
            /** Version */
            version: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Days */
            days: components["schemas"]["DayOut"][];
            /** Planner */
            planner: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Solve Ms */
            solve_ms: number;
            /**
             * Currency
             * @enum {string}
             */
            currency: "GBP" | "EUR" | "USD";
            targets: components["schemas"]["TargetsOut"];
            week_totals: components["schemas"]["MacrosOut"];
            /**
             * Cost Minor
             * @description estimated shopping cost
             */
            cost_minor: number;
            /** Budget Minor */
            budget_minor: number | null;
            /** Pantry Used G */
            pantry_used_g: number;
            /**
             * Waste G
             * @description pantry food that will expire unused within the plan
             */
            waste_g: number;
            /** Shopping Items */
            shopping_items: number;
            /** Excluded Allergens */
            excluded_allergens: components["schemas"]["Allergen"][];
            /** Diet */
            diet: ("vegetarian" | "vegan" | "pescatarian") | null;
            /** Violations */
            violations: components["schemas"]["ViolationOut"][];
            /** Notes */
            notes: string[];
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Start
             * @description first day (the user's local date, from yesterday to a week ahead); defaults to today (UTC)
             */
            start?: string | null;
        };
        /** PreferencesIn */
        PreferencesIn: {
            /** Diet */
            diet?: ("vegetarian" | "vegan" | "pescatarian") | null;
            /** Liked Cuisines */
            liked_cuisines?: string[];
            /** Disliked Cuisines */
            disliked_cuisines?: string[];
            /** Liked Food Ids */
            liked_food_ids?: number[];
            /** Disliked Food Ids */
            disliked_food_ids?: number[];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Diet */
            diet?: ("vegetarian" | "vegan" | "pescatarian") | null;
            /** Liked Cuisines */
            liked_cuisines?: string[];
            /** Disliked Cuisines */
            disliked_cuisines?: string[];
            /** Liked Food Ids */
            liked_food_ids?: number[];
            /** Disliked Food Ids */
            disliked_food_ids?: number[];
        };
        /**
         * Problems
         * @description 422 body for domain-rule failures (e.g. unsafe calorie targets).
         */
        Problems: {
            /** Detail */
            detail: string[];
        };
        /** ProfileStatus */
        ProfileStatus: {
            /** Has Goals */
            has_goals: boolean;
            /** Has Body */
            has_body: boolean;
            /** Has Allergies */
            has_allergies: boolean;
            /** Has Preferences */
            has_preferences: boolean;
            /** Pantry Items */
            pantry_items: number;
        };
        /** Readiness */
        Readiness: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checks */
            checks: {
                [key: string]: "ok" | "error";
            };
        };
        /** RecipeCard */
        RecipeCard: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Cuisine */
            cuisine: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** RecipeDetail */
        RecipeDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Cuisine */
            cuisine: string | null;
            /** Image Url */
            image_url: string | null;
            /** Instructions */
            instructions: string;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string | null;
            /** Servings */
            servings: number | null;
            /** Servings Estimated */
            servings_estimated: boolean;
            per_serving: components["schemas"]["MacrosOut"] | null;
            /** Meal Types */
            meal_types: components["schemas"]["Slot"][];
            /** Allergens */
            allergens: components["schemas"]["Allergen"][];
            /** Allergens Complete */
            allergens_complete: boolean;
            /** Suitable For */
            suitable_for: ("vegetarian" | "vegan" | "pescatarian")[];
            /** Ingredients */
            ingredients: components["schemas"]["RecipeIngredientOut"][];
        };
        /** RecipeIngredientOut */
        RecipeIngredientOut: {
            /** Name */
            name: string;
            /** Measure */
            measure: string;
            /** Food Id */
            food_id: number | null;
            /** Food Name */
            food_name: string | null;
            /** Grams */
            grams: number | null;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "female" | "male";
        /** ShoppingItemOut */
        ShoppingItemOut: {
            /** Food Id */
            food_id: number;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Grams */
            grams: number;
            /**
             * Cost Minor
             * @description share of total_minor; lines sum exactly to the total
             */
            cost_minor: number;
            /** Checked */
            checked: boolean;
            /**
             * Staple
             * @description store-cupboard item to check you have; no grams or cost
             */
            staple: boolean;
            /** Approx Units */
            approx_units?: string | null;
        };
        /** ShoppingItemPatch */
        ShoppingItemPatch: {
            /** Checked */
            checked: boolean;
        };
        /** ShoppingListOut */
        ShoppingListOut: {
            /** Plan Id */
            plan_id: number;
            /**
             * Currency
             * @enum {string}
             */
            currency: "GBP" | "EUR" | "USD";
            /**
             * Total Minor
             * @description estimated cost of every non-staple line (= plan cost)
             */
            total_minor: number;
            /** Budget Minor */
            budget_minor: number | null;
            /** Items */
            items: components["schemas"]["ShoppingItemOut"][];
        };
        /**
         * Slot
         * @description A meal of the day, in eating order.
         * @enum {string}
         */
        Slot: "breakfast" | "lunch" | "dinner" | "snack";
        /** SuggestedTargets */
        SuggestedTargets: {
            /** Kcal Min */
            kcal_min: number;
            /** Kcal Max */
            kcal_max: number;
            /** Protein G Min */
            protein_g_min: number | null;
        };
        /**
         * TargetsOut
         * @description What the planner aimed for: per-day bands, whole-plan bands, and the calorie floor.
         */
        TargetsOut: {
            daily: components["schemas"]["NutrientBands"];
            weekly: components["schemas"]["NutrientBands"];
            /** Calorie Floor */
            calorie_floor: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViolationOut
         * @description A rule the plan misses. `hard` ones (kcal band, budget, repeats) come only from the
         *     baseline planner; soft ones (protein/fat/carbs bands) are trade-offs any planner may make.
         *     Safety rules (allergens, diet, calorie floor) are never broken in a saved plan.
         */
        ViolationOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Hard */
            hard: boolean;
            /** Day */
            day?: number | null;
            slot?: components["schemas"]["Slot"] | null;
            /** Recipe Id */
            recipe_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsOut"] | null;
                };
            };
        };
    };
    putGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyOut"] | null;
                };
            };
        };
    };
    putBody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteBody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"] | null;
                };
            };
        };
    };
    putPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAllergies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergiesOut"] | null;
                };
            };
        };
    };
    putAllergies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllergiesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergiesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCuisines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    listAllergens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergenOption"][];
                };
            };
        };
    };
    searchFoods: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getFood: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPantry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemOut"][];
                };
            };
        };
    };
    addPantryItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletePantryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updatePantryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description bad start date, or no plan fits (reasons) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description setup incomplete (goals, allergies, preferences) or goals need review */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the planner found no plan in time */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problems"];
                };
            };
        };
    };
    getCurrentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"] | null;
                };
            };
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patchShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
                food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
