"""Weekly meal planning: the problem contract, the CP-SAT planner, the greedy baseline, the
independent validator and the infeasibility diagnosis."""

from larder_solver.baseline import greedy
from larder_solver.diagnose import diagnose
from larder_solver.metrics import Score, score
from larder_solver.problem import (
    HARD_NUTRIENTS,
    SLOT_ORDER,
    Allergen,
    AnimalTag,
    Band,
    Catalog,
    Diet,
    Food,
    Ingredient,
    Lot,
    Macros,
    Meal,
    Nutrient,
    Plan,
    PlanResult,
    Problem,
    Profile,
    Recipe,
    Slot,
    SlotSpec,
    Status,
    Targets,
    Weights,
    check_problem,
)
from larder_solver.shopping import ShoppingLine, ShoppingList, shopping_list
from larder_solver.solve import solve
from larder_solver.validate import (
    HARD_FILTER_CODES,
    SAFETY_CODES,
    STRUCTURAL_CODES,
    Code,
    Violation,
    hard,
    validate,
)

__all__ = [
    "HARD_FILTER_CODES",
    "HARD_NUTRIENTS",
    "SAFETY_CODES",
    "SLOT_ORDER",
    "STRUCTURAL_CODES",
    "Allergen",
    "AnimalTag",
    "Band",
    "Catalog",
    "Code",
    "Diet",
    "Food",
    "Ingredient",
    "Lot",
    "Macros",
    "Meal",
    "Nutrient",
    "Plan",
    "PlanResult",
    "Problem",
    "Profile",
    "Recipe",
    "Score",
    "ShoppingLine",
    "ShoppingList",
    "Slot",
    "SlotSpec",
    "Status",
    "Targets",
    "Violation",
    "Weights",
    "check_problem",
    "diagnose",
    "greedy",
    "hard",
    "score",
    "shopping_list",
    "solve",
    "validate",
]
